{% set version = "1.3.1" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-aod
  version: {{ version|replace("-", "_") }}

source:
  fn: aod_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/aod_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/aod/aod_{{ version }}.tar.gz
  sha256: 052d8802500fcfdb3b37a8e3e6f3fbd5c3a54e48c3f68122402d2ea3a15403bc

build:
  noarch: generic
  number: 2

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('aod')"  # [not win]
    - "\"%R%\" -e \"library('aod')\""  # [win]

about:
  home: http://cran.r-project.org/package=aod
  license: GPL (>= 2)
  summary: This package provides a set of functions to analyse overdispersed counts or proportions.
    Most of the methods are already available elsewhere but are scattered in different
    packages. The proposed functions should be considered as complements to more sophisticated
    methods such as generalized estimating equations (GEE) or generalized linear mixed
    effect models (GLMM).
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
