appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: efzFFN8E4BwRltz0X1eOrsec4vfuiEf2/k1+alGR5HosXdvEpnfvqyP20eZmwDoC3ji7GlGibJYJdpdgHnf0X7Tcxu97leypRI7KCoS+BGfkY5LvknMGY3YSJ+JYhjFP49u34nTgvml5L2zaEH+bUaW/3+CxRCV1Nmto0OlHkJYpDK4cH6k2D1RRFC6qdPkN7/fBUNbyMGW8TnAwsk0cFuQDp7LGqpqNEh2j07+zN2YNArUZFq6tblwBKs27zuc8RkGa9n1TxJx7eRnFDJB2Ov/oqMwaO7w1iOLBAuMDCCcq4vi0G/l3zpnQlaR71LMmv3r7FIEolJnc93UKzaCuaFz26LFqCWgc6fMYZKHcYficWk5SRh7PQrOYTBQKq9vUsoMFnZ0VRv9KGQdKHSP6OiMKgVx/+LsvUmLNFseAExhYJ0sXQWN4VDkAEnpZAE0KxnGMQBXm4WESjADQ9Lt8fXHflpjdYYwA/PXdq3a1N0yMEBS8QSdxav9il/GINdJQbR5LC4Ep5Q+AJ/UDZusP0W1xYvf3DdfTZCeGNklZh5x5pQzKElzsXYeS3ArKaHH8b1vRGkiNZakaKwlwNsbXQY1Vvo5UE2uhqf3HcTh0oNR+kbLTjurtj4fHvoF+6JDw30kwvmdBWh+xAvhGnBIl6GrpKrkpZTiOSyWX3T1ffUc=}
